---
- name: Install global Yarn packages.
  community.general.yarn:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: yes
  loop: "{{ yarn_packages }}"
